# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-08-18 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(choices=[('bing', 'Bing'), ('google', 'Google'), ('majestic', 'Majestic'), ('yandex', 'Yandex'), ('alexa', 'Alexa')], db_index=True, max_length=200, verbose_name='Поисковик')),
                ('code', models.CharField(db_index=True, max_length=200, verbose_name='Код')),
            ],
        ),
    ]
